/**
 * Dirpack Extension for Pi
 *
 * On session start, runs `dirpack pack` to build a compact repo index
 * and injects it into the system prompt via before_agent_start.
 * Gives the agent an instant map of the entire codebase structure.
 *
 * Requirements:
 *   - dirpack binary on PATH (https://github.com/rawwerks/dirpack)
 *
 * Install globally:
 *   Place at ~/.pi/agent/extensions/dirpack.ts
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execSync } from "node:child_process";

const TOKEN_BUDGET = 4000;

export default function dirpackExtension(pi: ExtensionAPI) {
  let dirpackAvailable = false;
  let repoIndex = "";

  pi.on("session_start", async (_event, ctx) => {
    // Check if dirpack is on PATH
    try {
      execSync("which dirpack", { stdio: "pipe" });
      dirpackAvailable = true;
    } catch {
      dirpackAvailable = false;
      return;
    }

    // Build the index synchronously (fast — typically <2s even for large repos)
    try {
      repoIndex = execSync(`dirpack pack -t ${TOKEN_BUDGET} -q`, {
        cwd: ctx.cwd,
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 10_000,
      }).toString().trim();
    } catch {
      repoIndex = "";
    }

    if (repoIndex) {
      ctx.ui.notify("dirpack: repo index loaded ✓", "info");
    }
  });

  pi.on("before_agent_start", async (event) => {
    if (!dirpackAvailable || !repoIndex) return;

    return {
      systemPrompt: event.systemPrompt + `

## Repository Index (dirpack)

Below is a compact index of the current repository's structure and key signatures,
generated by \`dirpack\`. Use this to orient yourself before searching or reading files.
Re-run \`dirpack pack\` if you need a fresh or more detailed view.

\`\`\`
${repoIndex}
\`\`\`
`,
    };
  });
}
